<a href="https://colab.research.google.com/github/yashMaheshBangera/large-behavior-model-twin2k/blob/main/notebooks/01_explore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exploratory Data Analysis (EDA)

In [1]:
from datasets import load_dataset

In [2]:
fp_data = load_dataset("LLM-Digital-Twin/Twin-2K-500","full_persona")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/11.0k [00:00<?, ?B/s]

full_persona/chunks/persona_chunk_001.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_001.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_002.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_002.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_003.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_003.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_004.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_004.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_005.pa(…): reconstructing file:   0%|          |  0.00B / 29.1MB

full_persona/chunks/persona_chunk_005.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_006.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_006.pa(…): downloading bytes:           |  0.00B

full_persona/chunks/persona_chunk_007.pa(…): reconstructing file:   0%|          |  0.00B / 29.0MB

full_persona/chunks/persona_chunk_007.pa(…): downloading bytes:           |  0.00B

Generating data split:   0%|          | 0/2058 [00:00<?, ? examples/s]

In [3]:
ws_data = load_dataset("LLM-Digital-Twin/Twin-2K-500","wave_split")

wave_split/chunks/wave_persona_chunk_001(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_001(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_002(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_002(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_003(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_003(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_004(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_004(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_005(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_005(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_006(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_006(…): downloading bytes:           |  0.00B

wave_split/chunks/wave_persona_chunk_007(…): reconstructing file:   0%|          |  0.00B / 27.0MB

wave_split/chunks/wave_persona_chunk_007(…): downloading bytes:           |  0.00B

Generating data split:   0%|          | 0/2058 [00:00<?, ? examples/s]

In [4]:
fp_data["data"]["pid"]

Column(['574', '2001', '1710', '1277', '789', ...])

In [5]:
ws_data

DatasetDict({
    data: Dataset({
        features: ['pid', 'wave1_3_persona_text', 'wave1_3_persona_json', 'wave4_Q_wave1_3_A', 'wave4_Q_wave4_A'],
        num_rows: 2058
    })
})

In [6]:
fp_df = fp_data["data"].to_pandas()
ws_df = ws_data["data"].to_pandas()

In [7]:
fp_df.columns

Index(['pid', 'persona_text', 'persona_summary', 'persona_json'], dtype='object')

In [8]:
ws_df.columns

Index(['pid', 'wave1_3_persona_text', 'wave1_3_persona_json',
       'wave4_Q_wave1_3_A', 'wave4_Q_wave4_A'],
      dtype='object')

In [9]:
# Checking if there are duplicate p_id values
fp_n_unique_pid = fp_df.pid.nunique()
if (fp_n_unique_pid==len(fp_df)):
  print("For full_persona : No duplicate p_id values found.")
else:
  print("For full_persona : Duplicate p_id values found!")
ws_n_unique_pid = ws_df.pid.nunique()
if (ws_n_unique_pid==len(ws_df)):
  print("For wave_split : No duplicate p_id values found.")
else:
  print("For wave_split : Duplicate p_id values found!")

For full_persona : No duplicate p_id values found.
For wave_split : No duplicate p_id values found.

In [10]:
import json

In [11]:
def check_unique_list(df,block_names,count):
  fp_persona_sample = json.loads(df["persona_json"][count])
  current_block_names = []
  for i in fp_persona_sample:
    current_block_names.append(i["BlockName"])
  return current_block_names

In [12]:
block_names = []
for count in range(0,len(fp_df),1):
  current_block_names = check_unique_list(fp_df,block_names,count)
  block_names.append(current_block_names)

In [13]:
#Checking if the block_names match for any ids
block_names[0][0]

'Demographics'

In [14]:
block_names[2057][2]

'Cognitive tests '

In [15]:
#Checking the length of each unique block name
count_arr = []
for i in range(len(block_names)):
  count_arr.append(len(block_names[i]))
unique_flag = set(count_arr)
print(unique_flag)

{30, 31}

In [16]:
print("Number of times 31 count array appears : " + str(count_arr.count(30)))
print("Number of times 32 count array appears : " + str(count_arr.count(31)))

Number of times 31 count array appears : 6
Number of times 32 count array appears : 2052

In [17]:
#Getting indices which are missing the last row
indices_31 = []
for i in range(len(count_arr)):
  if count_arr[i]==30:
    indices_31.append(i)

In [18]:
indices_31

[156, 395, 421, 686, 796, 941]

In [19]:
#Reviewing what is missing as compared to block_names[0]
for i in indices_31:
  print(block_names[i])
print(block_names[0])

['Demographics', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences ', 'False consensus ', 'Base-rate 70 engineers', 'Disease-loss', 'Linda -no conjunction ', 'Outcome bias - success ', 'Anchoring - African countries low ', 'Anchoring - redwood low', 'Less is More Gamble B ', 'Proportion dominance 1B', 'Proportion dominance 2B ', 'Sunk cost - no', 'Absolute vs. relative - calculator', 'WTA/WTP Thaler - WTP noncertainty', 'Allais Form 1', 'Myside German', 'Probability matching vs. maximizing - Problem 1', 'Non-experimental heuristics and biases ', 'Product Preferences - Pricing']
['Demographics', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Forward Flow', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Economic preferences ', 'False consensus ', 'Base-rate 70 engineers', 'Disease-loss', 'Linda -no conjunction ', 'Outcome bias - failure', 'Anchoring - African countries high', 'Anchoring - redwood high', 'Less is More Gamble A ', 'Proportion dominance 1A ', 'Proportion dominance 2A', 'Sunk cost - no', 'Absolute vs. relative - jacket', 'WTA/WTP Thaler problem - WTP certainty', 'Allais Form 2', 'Myside Ford', 'Probability matching vs. maximizing - Problem 2', 'Non-experimental heuristics and biases ', 'Product Preferences - Pricing']
['Demographics', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences ', 'False consensus ', 'Base-rate 30 engineers ', 'Disease - gain ', 'Linda -no conjunction ', 'Outcome bias - success ', 'Anchoring - African countries low ', 'Anchoring - redwood high', 'Less is More Gamble C ', 'Proportion dominance 1C', 'Proportion dominance 2C', 'Sunk cost - yes', 'Absolute vs. relative - jacket', 'WTA/WTP Thaler - WTP noncertainty', 'Allais Form 2', 'Myside German', 'Probability matching vs. maximizing - Problem 1', 'Non-experimental heuristics and biases ', 'Product Preferences - Pricing']
['Demographics', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences ', 'False consensus ', 'Base-rate 30 engineers ', 'Disease-loss', 'Linda -no conjunction ', 'Outcome bias - success ', 'Anchoring - African countries low ', 'Anchoring - redwood high', 'Less is More Gamble B ', 'Proportion dominance 1B', 'Proportion dominance 2B ', 'Sunk cost - no', 'Absolute vs. relative - jacket', 'WTA/WTP Thaler problem - WTA certainty', 'Allais Form 1', 'Myside Ford', 'Probability matching vs. maximizing - Problem 1', 'Non-experimental heuristics and biases ', 'Product Preferences - Pricing']
['Demographics', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences ', 'False consensus ', 'Base-rate 30 engineers ', 'Disease-loss', 'Linda-conjunction', 'Outcome bias - failure', 'Anchoring - African countries low ', 'Anchoring - redwood low', 'Less is More Gamble C ', 'Proportion dominance 1C', 'Proportion dominance 2C', 'Sunk cost - no', 'Absolute vs. relative - jacket', 'WTA/WTP Thaler problem - WTP certainty', 'Allais Form 2', 'Myside German', 'Probability matching vs. maximizing - Problem 2', 'Non-experimental heuristics and biases ', 'Product Preferences - Pricing']
['Demographics', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences ', 'False consensus ', 'Base-rate 70 engineers', 'Disease-loss', 'Linda-conjunction', 'Outcome bias - success ', 'Anchoring - African countries high', 'Anchoring - redwood low', 'Less is More Gamble B ', 'Proportion dominance 1B', 'Proportion dominance 2B ', 'Sunk cost - no', 'Absolute vs. relative - calculator', 'WTA/WTP Thaler problem - WTA certainty', 'Allais Form 2', 'Myside German', 'Probability matching vs. maximizing - Problem 1', 'Non-experimental heuristics and biases ', 'Product Preferences - Pricing']
['Demographics', 'Personality ', 'Cognitive tests ', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Forward Flow', 'Economic preferences - intro ', 'Economic preferences ', 'Personality ', 'Cognitive tests ', 'Economic preferences ', 'False consensus ', 'Base-rate 70 engineers', 'Disease-loss', 'Linda-conjunction', 'Outcome bias - success ', 'Anchoring - African countries low ', 'Anchoring - redwood low', 'Less is More Gamble C ', 'Proportion dominance 1C', 'Proportion dominance 2C', 'Sunk cost - yes', 'Absolute vs. relative - jacket', 'WTA/WTP Thaler problem - WTA certainty', 'Allais Form 1', 'Myside German', 'Probability matching vs. maximizing - Problem 1', 'Non-experimental heuristics and biases ', 'Product Preferences - Pricing']

In [20]:
#Looking at one of the question's structure for parsing the data

In [21]:
first_person = json.loads(fp_df["persona_json"][0])

In [22]:
import pandas as pd

In [23]:
first_person_df = pd.DataFrame(first_person)

In [24]:
first_person_df_questions = first_person_df["Questions"]

In [25]:
first_person_df_questions[0]

[{'QuestionID': 'QID11',
  'QuestionText': 'Which part of the United States do you currently live in?',
  'QuestionType': 'MC',
  'Options': ['Northeast (PA, NY, NJ, RI, CT, MA, VT, NH, ME)',
   'Midwest (ND, SD, NE, KS, MN, IA, MO, WI, IL, MI, IN, OH)',
   'South (TX, OK, AR, LA, KY, TN, MS, AL, WV, DC, MD, DE, VA, NC, SC, GA, FL)',
   'West (WA, OR, ID, MT, WY, CA, NV, UT, CO, AZ, NM)',
   'Pacific (HI, AK)'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 3,
   'SelectedText': 'South (TX, OK, AR, LA, KY, TN, MS, AL, WV, DC, MD, DE, VA, NC, SC, GA, FL)'}},
 {'QuestionID': 'QID12',
  'QuestionText': 'What is the sex that you were assigned at birth?',
  'QuestionType': 'MC',
  'Options': ['Male', 'Female'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 1, 'SelectedText': 'Male'}},
 {'QuestionID': 'QID13',
  'QuestionText': 'How old are you?',
  'QuestionType': 'MC',
  'Options': ['18-29', '30-49', '50-64', '65+'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 1, 'SelectedText': '18-29'}},
 {'QuestionID': 'QID14',
  'QuestionText': 'What is the highest level of schooling or degree that you have completed?',
  'QuestionType': 'MC',
  'Options': ['Less than high school',
   'High school graduate',
   'Some college, no degree',
   "Associate's degree",
   'College graduate/some postgrad',
   'Postgraduate'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 3,
   'SelectedText': 'Some college, no degree'}},
 {'QuestionID': 'QID15',
  'QuestionText': 'What is your race or origin?',
  'QuestionType': 'MC',
  'Options': ['White', 'Black', 'Asian', 'Hispanic', 'Other'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 1, 'SelectedText': 'White'}},
 {'QuestionID': 'QID16',
  'QuestionText': 'Are you a citizen of the United States?',
  'QuestionType': 'MC',
  'Options': ['Yes', 'No'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 1, 'SelectedText': 'Yes'}},
 {'QuestionID': 'QID17',
  'QuestionText': 'Which of these best describes you?',
  'QuestionType': 'MC',
  'Options': ['Married',
   'Living with a partner',
   'Divorced',
   'Separated',
   'Widowed',
   'Never been married'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 6, 'SelectedText': 'Never been married'}},
 {'QuestionID': 'QID18',
  'QuestionText': 'What is your present religion, if any?',
  'QuestionType': 'MC',
  'Options': ['Protestant',
   'Roman Catholic',
   'Mormon',
   'Orthodox',
   'Jewish',
   'Muslim',
   'Buddhist',
   'Hindu',
   'Atheist',
   'Agnostic',
   'Other',
   'Nothing in particular'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 1, 'SelectedText': 'Protestant'}},
 {'QuestionID': 'QID19',
  'QuestionText': 'Aside from weddings and funerals, how often do you attend religious services?',
  'QuestionType': 'MC',
  'Options': ['More than once a week',
   'Once a week',
   'Once or twice a month',
   'A few times a year',
   'Seldom',
   'Never'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 3,
   'SelectedText': 'Once or twice a month'}},
 {'QuestionID': 'QID20',
  'QuestionText': 'In politics today, do you consider yourself a',
  'QuestionType': 'MC',
  'Options': ['Republican', 'Democrat', 'Independent', 'Something else'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 1, 'SelectedText': 'Republican'}},
 {'QuestionID': 'QID21',
  'QuestionText': 'Last year, what was your total family income from all sources, before taxes?',
  'QuestionType': 'MC',
  'Options': ['Less than $30,000',
   '$30,000-$50,000',
   '$50,000-$75,000',
   '$75,000-$100,000',
   '$100,000 or more'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 5, 'SelectedText': '$100,000 or more'}},
 {'QuestionID': 'QID22',
  'QuestionText': 'In general, would you describe your political views as',
  'QuestionType': 'MC',
  'Options': ['Very conservative',
   'Conservative',
   'Moderate',
   'Liberal',
   'Very liberal'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 2, 'SelectedText': 'Conservative'}},
 {'QuestionID': 'QID23',
  'QuestionText': 'Including yourself, how many people currently live in your household?',
  'QuestionType': 'MC',
  'Options': ['1', '2', '3', '4', 'More than 4'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 4, 'SelectedText': '4'}},
 {'QuestionID': 'QID24',
  'QuestionText': 'What is your current employment status?',
  'QuestionType': 'MC',
  'Options': ['Full-time employment',
   'Part-time employment',
   'Unemployed',
   'Self-employed',
   'Home-maker',
   'Student',
   'Retired'],
  'Settings': {'Selector': 'SAVR', 'SubSelector': 'TX', 'ForceResponse': 'ON'},
  'Answers': {'SelectedByPosition': 6, 'SelectedText': 'Student'}}]

In [26]:
fp_df

,pid,persona_text,persona_summary,persona_json
0,574,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
1,2001,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
2,1710,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
3,1277,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
4,789,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
...,...,...,...,...
2053,883,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
2054,1500,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
2055,764,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
2056,1854,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."
2057,1029,Which part of the United States do you current...,The following is a description of a person.\n\...,"[{""ElementType"": ""Block"", ""BlockName"": ""Demogr..."

In [144]:
current_persona_df

,ElementType,BlockName,BlockType,Questions
0,Block,Demographics,Standard,"{'QuestionID': 'QID11', 'QuestionText': 'Which..."
1,Block,Demographics,Standard,"{'QuestionID': 'QID12', 'QuestionText': 'What ..."
2,Block,Demographics,Standard,"{'QuestionID': 'QID13', 'QuestionText': 'How o..."
3,Block,Demographics,Standard,"{'QuestionID': 'QID14', 'QuestionText': 'What ..."
4,Block,Demographics,Standard,"{'QuestionID': 'QID15', 'QuestionText': 'What ..."
5,Block,Demographics,Standard,"{'QuestionID': 'QID16', 'QuestionText': 'Are y..."
6,Block,Demographics,Standard,"{'QuestionID': 'QID17', 'QuestionText': 'Which..."
7,Block,Demographics,Standard,"{'QuestionID': 'QID18', 'QuestionText': 'What ..."
8,Block,Demographics,Standard,"{'QuestionID': 'QID19', 'QuestionText': 'Aside..."
9,Block,Demographics,Standard,"{'QuestionID': 'QID20', 'QuestionText': 'In po..."
10,Block,Demographics,Standard,"{'QuestionID': 'QID21', 'QuestionText': 'Last ..."
11,Block,Demographics,Standard,"{'QuestionID': 'QID22', 'QuestionText': 'In ge..."
12,Block,Demographics,Standard,"{'QuestionID': 'QID23', 'QuestionText': 'Inclu..."
13,Block,Demographics,Standard,"{'QuestionID': 'QID24', 'QuestionText': 'What ..."

In [197]:
def parse_extract_questions(df):
  num_rows = len(df)
  parsed_questions = []
  for i in range(0,num_rows,1):
    current_pid = df["pid"].iloc[i]
    current_persona = df["persona_json"].iloc[i]
    current_persona = json.loads(current_persona)
    current_persona_df = pd.DataFrame(current_persona)
    len_current_persona_df = len(current_persona_df)
    print(len_current_persona_df)
    for k in range(0,len_current_persona_df,1):
        current_dictionary = {
            "pid":current_pid,
            "qID":current_persona_df["Questions"].iloc[k][0]["QuestionID"],
            "qtext":current_persona_df["Questions"].iloc[k][0]["QuestionText"],
            "qtype":current_persona_df["Questions"].iloc[k][0]["QuestionType"],
            #"options":current_persona_df["Questions"].iloc[k][0]["Options"],
            "settings_selector":current_persona_df["Questions"].iloc[k][0]["Settings"]["Selector"],
            "settings_subSelector":current_persona_df["Questions"].iloc[k][0]["Settings"]["SubSelector"],
            "settings_forceResponse":current_persona_df["Questions"].iloc[k][0]["Settings"]["ForceResponse"],
            "answers_selected_position":current_persona_df["Questions"].iloc[k][0]["Answers"]["SelectedByPosition"],
            "answers_selected_text":current_persona_df["Questions"].iloc[k][0]["Answers"]["SelectedText"]
        }
        parsed_questions.append(pd.DataFrame(current_dictionary))
  return parsed_questions

In [198]:
parsed_questions = parse_extract_questions(fp_df)

31

ValueError: If using all scalar values, you must pass an index

In [173]:
current_persona = json.loads(fp_df["persona_json"].iloc[156])

In [179]:
current_persona_df = pd.DataFrame(current_persona)

In [192]:
current_persona_df["Questions"].iloc[0][0]["QuestionID"]

'QID11'

In [162]:
current_persona_0

'['